mappagofacil/map/urls.py
from django.conf.urls import patterns, url
from .views import OfficeListView, homeView, OfficeMap
urlpatterns = patterns('',
                       url(r'^$', homeView, name='home'),
                       url(r'^list$', OfficeListView.as_view(), name='list'),
                       url(r'^map/(?P<pk>\d+)$', OfficeMap.as_view(), name='office_map'),
                       )

mappagofacil/mappagofacil/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# ... the rest of your URLconf here ...





urlpatterns = patterns('',
                       url(r'^', include('map.urls')),
                       )

urlpatterns += staticfiles_urlpatterns()

mappagofacil/map/models.py
from django.db import models

# Create your models here.

mappagofacil/scrappagofacilmodels/models.py
from django.db import models
from jsonfield import JSONField


class Office(models.Model):
    city = models.CharField(max_length=100)
    province = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    scrapped = JSONField()

    def __str__(self):
        return "Office[city='{}', province='{}', address='{}', name='{}']".format(self.city, self.province, self.address, self.name)

    class Meta:
        ordering = ['province', 'city', 'address']

mappagofacil/map/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.db.models import Q
from scrappagofacilmodels.models import Office
import logging


logger = logging.getLogger(__name__)


class OfficeListView(ListView):
    model = Office
    paginate_by = 10
    template_name = 'map/list.html'

    def get_queryset(self):
        queryset = super(OfficeListView, self).get_queryset()
        q = self.request.GET.get("search_by")
        if q:
            return queryset.filter(Q(city__icontains=q) |
                                   Q(province__icontains=q) |
                                   Q(address__icontains=q))
        return queryset


def homeView(request):
    return render(request, 'map/home.html')


class OfficeMap(DetailView):
    model = Office
    template_name = 'map/office_detail.html'

mappagofacil/scrappagofacilmodels/views.py
from django.shortcuts import render

# Create your views here.

mappagofacil/map/templates/map/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Oficinas RapiPago{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    {% block extracss %}{% endblock extracss %}
    {% block extrajs_head %}{% endblock extrajs_head %}
    <body>
    <div class="container">
        {% block search_box %}
            <div class='row '>
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h2>Oficinas RapiPago</h2>
                        <form action="{% url 'list' %}" method='GET'>
                            <input type="text" id='search_by' name='search_by' placeholder='Search by...'>
                            <button type="submit" id="btn-search" class='btn btn-default'>Buscar</button>
                        </form>
                    </div>
                </div>            
            </div>
        {% endblock search_box %}
        {% block content %}
        {% endblock content %}
    </div>
    {% block extrajs_footer %}{% endblock extrajs_footer %}
</body>

</html>

mappagofacil/map/templates/map/home.html
{% extends 'map/base.html' %}
{% load static from staticfiles %}

mappagofacil/map/templates/map/list.html
{% extends 'map/base.html' %}
{% load static from staticfiles %}
{% block content %}
<row>
        <div class="text-left">
        {% regroup office_list by province as province_list %}
        {% for province in province_list %}

        <div id='province_{{ forloop.counter }}'  name='province_{{ forloop.counter }}'  class='province'>
        <span class='name'>
        <h3>{{ province.grouper }}</h3>
        </span>
        {% regroup province.list by city as city_list %}
            {% for city in city_list %}
            <div class='city'>
                <h4>{{ city.grouper }} </h4>
            </div>
                {% for office in city.list  %}
                <div class='address'>
                    {{ office.address   }}
                    <a href="/map">View In Map</a>
                </div>
                    
                {% endfor %}
            {%endfor%}
         </div>
         </div>
    {%endfor%}
    </row>
    <row >
    <div class="footer navbar navbar-default navbar-fixed-bottom">
    <div class="container">
    <nav>
     <ul class="pagination">
     <li class="{% if  not page_obj.has_previous %}disabled{% endif %}"><a name='previous' {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}{% endif %}">previous</a></li>

    {% with lower=page_obj.number|add:"-5"  upper=page_obj.number|add:"5"%}
    {% for pagenr in paginator.page_range  %}
     <li class="{% if pagenr == page_obj.number %}active{% endif %}"><a name='page_{{pagenr}}' href="?page={{ pagenr }}">{{pagenr}}</a></li>
    {% endfor %}
    {% endwith %}
     <li class="{% if not page_obj.has_next %}disabled{% endif %}"><a name='next' {% if  page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>next</a></li>
    
    
</ul>
    </nav>
    </div>

    </div>
    </row>
    {% endblock content %}

mappagofacil/map/templates/map/office_detail.html
{% extends 'map/base.html' %}
{% load static from staticfiles %}
{% block extrajs_head %}  
{% load map_tags %}
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyDzFVT-N7B6O8MdAdmxfodQu7MmG8ZaZ6w&sensor=false" ></script> 
<script src="{% static 'js/map.js' %}"></script>
{% endblock extrajs_head %}
{% block extracss %}
<style>
    html, body, .container, .row, #map_canvas , .col-sm-9  { height: 100% }
</style>
{% endblock extracss %}
{% block search_box %}{% endblock search_box %}
{% block content %}

<div class='row'>
        <div class="col-sm-9">
            <div class="panel panel-info">
                <div class='panel-heading'>
                <h4>Datos oficina</h4>
                </div>

                    <div class='panel-body'>
                            <div class='name'>
                                 <label>Nombre:</label>
                                <span id='name' class='text-info'>{{ office.name   }}</span>
                            </div>                    

                            <div class='province'>
                                <label>Provincia:</label>
                                <span id='province' class='text-info'>{{ office.province   }}</span>
                            </div>                    
                            <div class='city'>
                                <label>Ciudad:</label>
                                <span id='city' class='text-info'>{{ office.city   }}</span>
                            </div>                    

                            <div class='address'>
                                <label>Dirección:</label>
                                <span id='address' class='text-info'>{{ office.address   }}</span>
                            </div>                    
                    </div>
                 </div>
                 <div id='map_canvas' name='map_canvas'></div>
         </div>

    </div>
    {% endblock content %}
    {% block extrajs_footer %}
<script>
    var latlong, zoom, title, div_id;
    latlong = [-25.363882,131.044922]
    zoom = 12
    title = 'my office'
    div_id = 'map_canvas'

      $( document ).ready(function() {
          Map.initialize(latlong, zoom, title, div_id, {% map_optimized %} == 'true')
      }); 


</script>
    {% endblock extrajs_footer %}